export * from './address.model'
export * from './catalogue.model'
export * from './column.model'
export * from './file.model';
export * from './image.model';
export * from './location.model'
export * from './paginator.model';
export * from './phone.model';
export * from './state.model';
export * from './career.model';
export * from './signature.model';
export * from './student.model';
export * from './year.model';
export * from './teacher.model';
